import 'dotenv/config';
import { DataSource } from 'typeorm';
import { Department } from './src/database/entities/department.entity';
import { Municipality } from './src/database/entities/municipality.entity';

const departmentsData = [
  {
    name: 'Amazonas',
    municipalities: [
      'LETICIA',
      'PUERTO NARIÑO',
      'EL ENCANTO',
      'LA CHORRERA',
      'LA PEDRERA',
      'LA VICTORIA',
      'MIRITI PARANA',
      'PUERTO SANTANDER',
      'TARAPACA',
      'PUERTO ALEGRIA',
      'PUERTO ARICA',
    ],
  },
  {
    name: 'Antioquia',
    municipalities: [
      'MEDELLIN',
      'ABEJORRAL',
      'ABRIAQUI',
      'ALEJANDRIA',
      'AMAGA',
      'AMALFI',
      'ANDES',
      'ANGELOPOLIS',
      'ANGOSTURA',
      'ANORI',
      'ANTIOQUIA',
      'ANZA',
      'APARTADO',
      'ARBOLETES',
      'ARGELIA',
      'ARMENIA',
      'BARBOSA',
      'BELMIRA',
      'BELLO',
      'BETANIA',
      'BETULIA',
      'BOLIVAR',
      'BURITICA',
      'BRICEÑO',
      'CACERES',
      'CAICEDO',
      'CALDAS',
      'CAMPAMENTO',
      'CAÑASGORDAS',
      'CARACOLI',
      'CARAMANTA',
      'CAREPA',
      'CARMEN DE VIBORAL',
      'CAROLINA',
      'CAUCASIA',
      'CISNEROS',
      'COCORNA',
      'CONCEPCION',
      'CONCORDIA',
      'COPACABANA',
      'CHIGORODO',
      'DABEIBA',
      'DON MATIAS',
      'EBEJICO',
      'EL BAGRE',
      'ENTRERRIOS',
      'ENVIGADO',
      'FREDONIA',
      'FRONTINO',
      'GIRALDO',
      'GIRARDOTA',
      'GOMEZ PLATA',
      'GRANADA',
      'GUADALUPE',
      'GUARNE',
      'GUATAPE',
      'HELICONIA',
      'HISPANIA',
      'ITAGUI',
      'ITUANGO',
      'JARDIN',
      'JERICO',
      'LA CEJA',
      'LA ESTRELLA',
      'PUERTO NARE-LA MAGDALENA',
      'LA UNION',
      'LA PINTADA',
      'LIBORINA',
      'MACEO',
      'MARINILLA',
      'MONTEBELLO',
      'MURINDO',
      'MUTATA',
      'NARIÑO',
      'NECHI',
      'NECOCLI',
      'OLAYA',
      'PEÑOL',
      'PEQUE',
      'PUEBLORRICO',
      'PUERTO BERRIO',
      'PUERTO TRIUNFO',
      'REMEDIOS',
      'RETIRO',
      'RIONEGRO',
      'SABANALARGA',
      'SABANETA',
      'SALGAR',
      'SAN ANDRES',
      'SAN CARLOS',
      'SAN FRANCISCO',
      'SAN JERONIMO',
      'SAN JOSE DE LA MONTAÑA',
      'SAN JUAN DE URABA',
      'SAN LUIS',
      'SAN PEDRO',
      'SAN PEDRO DE URABA',
      'SAN RAFAEL',
      'SAN ROQUE',
      'SAN VICENTE',
      'SANTA BARBARA',
      'SANTA ROSA DE OSOS',
      'SANTO DOMINGO',
      'SANTUARIO',
      'SEGOVIA',
      'SONSON',
      'SOPETRAN',
      'TAMESIS',
      'TARAZA',
      'TARSO',
      'TITIRIBI',
      'TOLEDO',
      'TURBO',
      'URAMITA',
      'URRAO',
      'VALDIVIA',
      'VALPARAISO',
      'VEGACHI',
      'VIGIA DEL FUERTE',
      'VENECIA',
      'YALI',
      'YARUMAL',
      'YOLOMBO',
      'YONDO-CASABE',
      'ZARAGOZA',
    ],
  },
  {
    name: 'Arauca',
    municipalities: [
      'ARAUCA',
      'TAME',
      'ARAUQUITA',
      'CRAVO NORTE',
      'FORTUL',
      'PUERTO RONDON',
      'SARAVENA',
    ],
  },
  {
    name: 'Atlántico',
    municipalities: [
      'BARRANQUILLA',
      'BARANOA',
      'CAMPO DE LA CRUZ',
      'CANDELARIA',
      'GALAPA',
      'JUAN DE ACOSTA',
      'LURUACO',
      'MALAMBO',
      'MANATI',
      'PALMAR DE VARELA',
      'PIOJO',
      'POLONUEVO',
      'PONEDERA',
      'PUERTO COLOMBIA',
      'REPELON',
      'SABANAGRANDE',
      'SABANALARGA',
      'SANTA LUCIA',
      'SANTO TOMAS',
      'SOLEDAD',
      'SUAN',
      'TUBARA',
      'USIACURI',
    ],
  },
  {
    name: 'Bolívar',
    municipalities: [
      'ACHI',
      'ALTOS DEL ROSARIO',
      'ARENAL',
      'ARJONA',
      'ARROYO HONDO',
      'BARRANCO DE LOBA',
      'CALAMAR',
      'CANTAGALLO',
      'CARTAGENA',
      'CICUCO',
      'CLEMENCIA',
      'CORDOBA',
      'EL CARMEN DE BOLIVAR',
      'EL GUAMO',
      'EL PEÑON',
      'HATILLO DE LOBA',
      'MAGANGUE',
      'MAHATES',
      'MARGARITA',
      'MARIA LA BAJA',
      'MOMPOS',
      'MONTECRISTO',
      'MORALES',
      'NOROSI',
      'PINILLOS',
      'REGIDOR',
      'RIOVIEJO',
      'SAN CRISTOBAL',
      'SAN ESTANISLAO',
      'SAN FERNANDO',
      'SAN JACINTO',
      'SAN JACINTO DEL CAUCA',
      'SAN JUAN NEPOMUCENO',
      'SAN MARTIN DE LOBA',
      'SAN PABLO',
      'SANTA CATALINA',
      'SANTA ROSA',
      'SANTA ROSA DEL SUR',
      'SIMITI',
      'SOPLAVIENTO',
      'TALAIGUA NUEVO',
      'TIQUISIO (PTO. RICO)',
      'TURBACO',
      'TURBANA',
      'VILLANUEVA',
      'ZAMBRANO',
    ],
  },
  {
    name: 'Boyacá',
    municipalities: [
      'Almeida',
      'Aquitania',
      'Arcabuco',
      'Belén',
      'Berbeo',
      'Betéitiva',
      'Boavita',
      'Boyacá',
      'Briceño',
      'Buenavista',
      'Busbanzá',
      'Caldas',
      'Campohermoso',
      'Cerinza',
      'Chinavita',
      'Chiquinquirá',
      'Chíquiza',
      'Chiscas',
      'Chita',
      'Chitaraque',
      'Chivatá',
      'Chivor',
      'Ciénega',
      'Cómbita',
      'Coper',
      'Corrales',
      'Covarachía',
      'Cubará',
      'Cucaita',
      'Cuítiva',
      'Duitama',
      'El Cocuy',
      'El Espino',
      'Firavitoba',
      'Floresta',
      'Gachantivá',
      'Gámeza',
      'Garagoa',
      'Guacamayas',
      'Guateque',
      'Guayatá',
      'Güicán',
      'Iza',
      'Jenesano',
      'Jericó',
      'Labranzagrande',
      'La Capilla',
      'La Uvita',
      'La Victoria',
      'Villa de Leyva',
      'Macanal',
      'Maripí',
      'Miraflores',
      'Mongua',
      'Monguí',
      'Moniquirá',
      'Motavita',
      'Muzo',
      'Nobsa',
      'Nuevo Colón',
      'Oicatá',
      'Otanche',
      'Pachavita',
      'Páez',
      'Paipa',
      'Pajarito',
      'Panqueba',
      'Pauna',
      'Paya',
      'Paz de Río',
      'Pesca',
      'Pisba',
      'Puerto Boyacá',
      'Quípama',
      'Ramiriquí',
      'Ráquira',
      'Rondón',
      'Saboyá',
      'Sáchica',
      'Samacá',
      'San Eduardo',
      'San José de Pare',
      'San Luis de Gaceno',
      'San Mateo',
      'San Miguel de Sema',
      'San Pablo de Borbur',
      'Santana',
      'Santa María',
      'Santa Rosa de Viterbo',
      'Santa Sofía',
      'Sativanorte',
      'Sativasur',
      'Siachoque',
      'Soatá',
      'Socotá',
      'Socha',
      'Sogamoso',
      'Somondoco',
      'Sora',
      'Soracá',
      'Sotaquirá',
      'Susacón',
      'Sutamarchán',
      'Sutatenza',
      'Tasco',
      'Tenza',
      'Tibaná',
      'Tibasosa',
      'Tinjacá',
      'Tipacoque',
      'Toca',
      'Togüí',
      'Tópaga',
      'Tota',
      'Tunja',
      'Tununguá',
      'Turmequé',
      'Tuta',
      'Tutazá',
      'Úmbita',
      'Ventaquemada',
      'Viracachá',
      'Zetaquira',
    ],
  },
  {
    name: 'Caldas',
    municipalities: [
      'Manizales',
      'Aguadas',
      'Anserma',
      'Aranzazu',
      'Belalcázar',
      'Chinchiná',
      'Filadelfia',
      'La Dorada',
      'La Merced',
      'Manzanares',
      'Marmato',
      'Marquetalia',
      'Marulanda',
      'Neira',
      'Norcasia',
      'Pácora',
      'Palestina',
      'Pensilvania',
      'Riosucio',
      'Risaralda',
      'Salamina',
      'Samaná',
      'San José',
      'Supía',
      'Victoria',
      'Villamaría',
      'Viterbo',
    ],
  },
  {
    name: 'Caquetá',
    municipalities: [
      'Florencia',
      'Albania',
      'Cartagena del Chairá',
      'Belén de los Andaquíes',
      'El Doncello',
      'El Paujil',
      'La Montañita',
      'Puerto Rico',
      'San Vicente del Caguán',
      'Curillo',
      'Milán',
      'Morelia',
      'San José del Fragua',
      'Solano',
      'Solita',
      'Valparaíso',
    ],
  },
  {
    name: 'Casanare',
    municipalities: [
      'Yopal',
      'Aguazul',
      'Chámeza',
      'Hato Corozal',
      'La Salina',
      'Maní',
      'Monterrey',
      'Nunchía',
      'Orocué',
      'Paz de Ariporo',
      'Pore',
      'Recetor',
      'Sabanalarga',
      'Sácama',
      'San Luis de Palenque',
      'Támara',
      'Tauramena',
      'Trinidad',
      'Villanueva',
    ],
  },
  {
    name: 'Cauca',
    municipalities: [
      'Popayán',
      'Almaguer',
      'Argelia',
      'Balboa',
      'Bolívar',
      'Buenos Aires',
      'Cajibío',
      'Caldono',
      'Caloto',
      'Corinto',
      'El Tambo',
      'Florencia',
      'Guapi',
      'Guachené',
      'Inzá',
      'Jambaló',
      'La Sierra',
      'La Vega',
      'López de Micay',
      'Mercaderes',
      'Miranda',
      'Morales',
      'Padilla',
      'Páez (Belalcázar)',
      'Patía (El Bordo)',
      'Piamonte',
      'Piendamó',
      'Puerto Tejada',
      'Puracé (Coconuco)',
      'Rosas',
      'San Sebastián',
      'Santander de Quilichao',
      'Santa Rosa',
      'Silvia',
      'Sotará (Paispamba)',
      'Sucre',
      'Suárez',
      'Timbío',
      'Timbiquí',
      'Toribío',
      'Totoró',
      'Villa Rica',
    ],
  },
  {
    name: 'Cesar',
    municipalities: [
      'Valledupar',
      'Aguachica',
      'Agustín Codazzi',
      'Astrea',
      'Becerril',
      'Bosconia',
      'Curumaní',
      'Chimichagua',
      'Chiriguaná',
      'El Copey',
      'El Paso',
      'Gamarra',
      'González',
      'La Gloria',
      'La Jagua de Ibirico',
      'Manaure Balcón del Cesar',
      'Pailitas',
      'Pelaya',
      'Pueblo Bello',
      'Río de Oro',
      'San Alberto',
      'La Paz',
      'San Diego',
      'San Martín',
      'Tamalameque',
    ],
  },
  {
    name: 'Chocó',
    municipalities: [
      'Quibdó',
      'Atrato (Yuto)',
      'Acandí',
      'Alto Baudó (Pie de Pató)',
      'Bagadó',
      'Bahía Solano (Mutis)',
      'Bajo Baudó (Pizarro)',
      'Bojayá (Bellavista)',
      'Medio Atrato (Beté)',
      'Condoto',
      'Cértegui',
      'Carmen del Darién',
      'El Carmen de Atrato',
      'El Cantón del San Pablo (Managrú)',
      'Istmina',
      'Juradó',
      'Lloró',
      'Medio Baudó (Puerto Meluk)',
      'Medio San Juan',
      'Nóvita',
      'Nuquí',
      'Río Iró',
      'Riosucio',
      'Río Quito (Paimadó)',
      'San José del Palmar',
      'El Litoral del San Juan',
      'Sipí',
      'Tadó',
      'Unguía',
      'Unión Panamericana (Las Ánimas)',
      'Nuevo Belén de Bajirá',
    ],
  },
  {
    name: 'Córdoba',
    municipalities: [
      'Montería',
      'Ayapel',
      'Buenavista',
      'Canalete',
      'Cereté',
      'Ciénaga de Oro',
      'Cotorra (Bongo)',
      'Chimá',
      'Chinú',
      'La Apartada (Frontera)',
      'Lorica',
      'Los Córdobas',
      'Momil',
      'Montelíbano',
      'Moñitos',
      'Planeta Rica',
      'Pueblo Nuevo',
      'Puerto Libertador',
      'Puerto Escondido',
      'Purísima',
      'Sahagún',
      'San Andrés de Sotavento',
      'San Antero',
      'San Bernardo del Viento',
      'San Carlos',
      'San José de Uré',
      'San Pelayo',
      'Tierralta',
      'Tuchín',
      'Valencia',
    ],
  },
  {
    name: 'Cundinamarca',
    municipalities: [
      'Agua de Dios',
      'Albán',
      'Anapoima',
      'Anolaima',
      'Arbeláez',
      'Beltrán',
      'Bituima',
      'Bojacá',
      'Cabrera',
      'Cachipay',
      'Cajicá',
      'Caparrapí',
      'Cáqueza',
      'Carmen de Carupa',
      'Cogua',
      'Cota',
      'Cucunubá',
      'Chaguaní',
      'Chía',
      'Chipaque',
      'Choachí',
      'Chocontá',
      'El Colegio',
      'El Peñón',
      'El Rosal',
      'Facatativá',
      'Fómeque',
      'Fosca',
      'Funza',
      'Fúquene',
      'Fusagasugá',
      'Gachalá',
      'Gachancipá',
      'Gachetá',
      'Gama',
      'Girardot',
      'Guachetá',
      'Guaduas',
      'Guasca',
      'Guataquí',
      'Guatavita',
      'Guayabal de Síquima',
      'Guayabetal',
      'Gutiérrez',
      'Granada',
      'Jerusalén',
      'Junín',
      'La Calera',
      'La Mesa',
      'La Palma',
      'La Peña',
      'La Vega',
      'Lenguazaque',
      'Machetá',
      'Madrid',
      'Manta',
      'Medina',
      'Mosquera',
      'Nariño',
      'Nemocón',
      'Nilo',
      'Nimaima',
      'Nocaima',
      'Pacho',
      'Paime',
      'Pandi',
      'Paratebueno',
      'Pasca',
      'Puerto Salgar',
      'Pulí',
      'Quebradanegra',
      'Quetame',
      'Quipile',
      'Apulo',
      'Ricaurte',
      'San Antonio del Tequendama',
      'San Bernardo',
      'San Cayetano',
      'San Francisco',
      'San Juan de Rioseco',
      'Sasaima',
      'Sesquilé',
      'Sibaté',
      'Silvania',
      'Simijaca',
      'Soacha',
      'Sopó',
      'Subachoque',
      'Suesca',
      'Supatá',
      'Susa',
      'Sutatausa',
      'Tabio',
      'Tausa',
      'Tena',
      'Tenjo',
      'Tibacuy',
      'Tibirita',
      'Tocaima',
      'Tocancipá',
      'Topaipí',
      'Ubalá',
      'Ubaque',
      'Ubaté',
      'Une',
      'Útica',
      'Venecia',
      'Vergara',
      'Vianí',
      'Villagómez',
      'Villapinzón',
      'Villeta',
      'Viotá',
      'Yacopí',
      'Zipacón',
      'Zipaquirá',
    ],
  },
  {
    name: 'Guainía',
    municipalities: [
      'Inírida',
      'Barrancominas',
      'Cacahual',
      'La Guadalupe',
      'Morichal (Morichal Nuevo)',
      'Pana Pana (Campo Alegre)',
      'Puerto Colombia',
      'San Felipe',
    ],
  },
  {
    name: 'Guaviare',
    municipalities: [
      'San José del Guaviare',
      'Calamar',
      'El Retorno',
      'Miraflores',
    ],
  },
  {
    name: 'Huila',
    municipalities: [
      'Neiva',
      'Acevedo',
      'Agrado',
      'Aipe',
      'Algeciras',
      'Altamira',
      'Baraya',
      'Campoalegre',
      'Tesalia (Carnicerías)',
      'Colombia',
      'Elías',
      'Garzón',
      'Gigante',
      'Guadalupe',
      'Hobo',
      'Isnos',
      'Íquira',
      'La Argentina (Plata Vieja)',
      'La Plata',
      'Nátaga',
      'Oporapa',
      'Paicol',
      'Palermo',
      'Palestina',
      'Pital',
      'Pitalito',
      'Rivera',
      'Saladoblanco',
      'San Agustín',
      'Santa María',
      'Suaza',
      'Tarqui',
      'Tello',
      'Teruel',
      'Timaná',
      'Villavieja',
      'Yaguará',
    ],
  },
  {
    name: 'La Guajira',
    municipalities: [
      'Riohacha',
      'Albania',
      'Barrancas',
      'Dibulla',
      'El Molino',
      'Fonseca',
      'Distracción',
      'Hatonuevo',
      'Maicao',
      'Manaure',
      'La Jagua del Pilar',
      'San Juan del Cesar',
      'Uribia',
      'Urumita',
      'Villanueva',
    ],
  },
  {
    name: 'Magdalena',
    municipalities: [
      'Santa Marta',
      'Algarrobo',
      'Aracataca',
      'Ariguaní (El Difícil)',
      'Cerro de San Antonio',
      'Chivolo',
      'Ciénaga',
      'Concordia',
      'El Banco',
      'El Piñón',
      'El Retén',
      'Fundación',
      'Guamal',
      'Nueva Granada',
      'Pedraza',
      'Pijiño del Carmen',
      'Pivijay',
      'Plato',
      'Puebloviejo',
      'Remolino',
      'Sabanas de San Ángel',
      'Salamina',
      'San Sebastián de Buenavista',
      'San Zenón',
      'Santa Ana',
      'Santa Bárbara de Pinto',
      'Sitionuevo',
      'Tenerife',
      'Zapayán',
      'Zona Bananera (Sevilla)',
    ],
  },
  {
    name: 'Meta',
    municipalities: [
      'Villavicencio',
      'Acacías',
      'Barranca de Upía',
      'Cabuyaro',
      'Castilla La Nueva',
      'Cubarral',
      'Cumaral',
      'El Calvario',
      'El Castillo',
      'El Dorado',
      'Fuente de Oro',
      'Granada',
      'Guamal',
      'La Macarena',
      'Lejanías',
      'Mapiripán',
      'Mesetas',
      'Puerto Concordia',
      'Puerto Gaitán',
      'Puerto Lleras',
      'Puerto López',
      'Puerto Rico',
      'Restrepo',
      'San Carlos de Guaroa',
      'San Juan de Arama',
      'San Juanito',
      'San Martín de los Llanos',
      'Uribe',
      'Vista Hermosa',
    ],
  },
  {
    name: 'Nariño',
    municipalities: [
      'Albán (San José)',
      'Aldana',
      'Ancuya',
      'Arboleda (Berruecos)',
      'Barbacoas',
      'Belén',
      'Buesaco',
      'Chachagui',
      'Colón (Génova)',
      'Consacá',
      'Contadero',
      'Córdoba',
      'Cuaspud (Carlosama)',
      'Cumbal',
      'Cumbitara',
      'El Charco',
      'El Peñol',
      'El Rosario',
      'El Tablón',
      'El Tambo',
      'Francisco Pizarro (Salahonda)',
      'Funes',
      'Guachucal',
      'Guaitarilla',
      'Gualmatan',
      'Iles',
      'Imues',
      'Ipiales',
      'La Cruz',
      'La Florida',
      'La Llanada',
      'La Tola',
      'La Unión',
      'Leiva',
      'Linares',
      'Los Andes (Sotomayor)',
      'Magüi (Payán)',
      'Mallama (Piedrancha)',
      'Mosquera',
      'Nariño',
      'Olaya Herrera',
      'Ospina',
      'Pasto',
      'Policarpa',
      'Potosí',
      'Providencia',
      'Puerres',
      'Pupiales',
      'Ricaurte',
      'Roberto Payán (San José)',
      'Samaniego',
      'Sandona',
      'San Bernardo',
      'San Lorenzo',
      'San Pablo',
      'San Pedro de Cartago',
      'Santa Bárbara (Iscuandé)',
      'Santacruz (Guachavés)',
      'Sapuyés',
      'Taminango',
      'Tangua',
      'Tumaco',
      'Tuquerres',
      'Yacuanquer',
    ],
  },
  {
    name: 'Norte de Santander',
    municipalities: [
      'Abrego',
      'Arboledas',
      'Bochalema',
      'Bucarasica',
      'Cácota',
      'Cáchira',
      'Chinácota',
      'Chitaga',
      'Convención',
      'Cúcuta',
      'Cucutilla',
      'Durania',
      'El Carmen',
      'El Tarra',
      'El Zulia',
      'Gramalote',
      'Hacari',
      'Herran',
      'Labateca',
      'La Esperanza',
      'La Playa',
      'Los Patios',
      'Lourdes',
      'Mutiscua',
      'Ocaña',
      'Pamplona',
      'Pamplonita',
      'Puerto Santander',
      'Ragonvalia',
      'Salazar',
      'San Calixto',
      'San Cayetano',
      'Santiago',
      'Sardinata',
      'Silos',
      'Teorama',
      'Tibú',
      'Toledo',
      'Villa Caro',
      'Villa del Rosario',
    ],
  },
  {
    name: 'Putumayo',
    municipalities: [
      'Colón',
      'Mocoa',
      'Orito',
      'Puerto Asís',
      'Puerto Caicedo',
      'Puerto Guzmán',
      'Puerto Leguizamo',
      'San Francisco',
      'San Miguel (La Dorada)',
      'Santiago',
      'Sibundoy',
      'Valle del Guamuez (La Hormiga)',
      'Villagarzón',
    ],
  },
  {
    name: 'Quindío',
    municipalities: [
      'Armenia',
      'Buenavista',
      'Calarcá',
      'Circasia',
      'Córdoba',
      'Filandia',
      'Génova',
      'La Tebaida',
      'Montenegro',
      'Pijao',
      'Quimbaya',
      'Salento',
    ],
  },
  {
    name: 'Risaralda',
    municipalities: [
      'Apía',
      'Balboa',
      'Belén de Umbría',
      'Dosquebradas',
      'Guática',
      'La Celia',
      'La Virginia',
      'Marsella',
      'Mistrató',
      'Pereira',
      'Pueblo Rico',
      'Quinchía',
      'Santa Rosa de Cabal',
      'Santuario',
    ],
  },
  {
    name: 'San Andrés y Providencia',
    municipalities: ['San Andrés', 'Providencia'],
  },
  {
    name: 'Santander',
    municipalities: [
      'Aguada',
      'Albania',
      'Aratoca',
      'Barbosa',
      'Barichara',
      'Barrancabermeja',
      'Betulia',
      'Bolívar',
      'Bucaramanga',
      'Cabrera',
      'California',
      'Capitanejo',
      'Carcasí',
      'Cepita',
      'Cerrito',
      'Charta',
      'Charala',
      'Chima',
      'Chipata',
      'Cimitarra',
      'Concepción',
      'Confines',
      'Contratación',
      'Coromoro',
      'Curití',
      'El Carmen',
      'El Guacamayo',
      'El Peñón',
      'El Playón',
      'Encino',
      'Enciso',
      'Florián',
      'Floridablanca',
      'Galán',
      'Gambita',
      'Girón',
      'Guaca',
      'Guadalupe',
      'Guapota',
      'Guavata',
      'Guepsa',
      'Hato',
      'Jesús María',
      'Jordán',
      'La Belleza',
      'La Paz',
      'Landázuri',
      'Lebrija',
      'Los Santos',
      'Macaravita',
      'Málaga',
      'Matanza',
      'Mogotes',
      'Molagavita',
      'Ocamonte',
      'Oiba',
      'Onzaga',
      'Palmar',
      'Palmas del Socorro',
      'Páramo',
      'Piedecuesta',
      'Pinchote',
      'Puente Nacional',
      'Puerto Parra',
      'Puerto Wilches',
      'Rionegro',
      'Sabana de Torres',
      'San Andrés',
      'San Benito',
      'San Gil',
      'San Joaquín',
      'San José de Miranda',
      'San Miguel',
      'San Vicente de Chucurí',
      'Santa Bárbara',
      'Santa Helena del Opón',
      'Simacota',
      'Socorro',
      'Suita',
      'Sucre',
      'Suratá',
      'Tona',
      'Valle de San José',
      'Vetas',
      'Vélez',
      'Villanueva',
      'Zapatoca',
    ],
  },
  {
    name: 'Sucre',
    municipalities: [
      'Buenavista',
      'Caimito',
      'Chalán',
      'Coloso (Ricaurte)',
      'Corozal',
      'Coveñas',
      'El Roble',
      'Galeras (Nueva Granada)',
      'Guaranda',
      'La Unión',
      'Los Palmitos',
      'Majagual',
      'Morroa',
      'Ovejas',
      'Palmito',
      'Sampués',
      'San Benito Abad',
      'San Juan de Betulia (Betulia)',
      'San Marcos',
      'San Onofre',
      'San Pedro',
      'Sincé',
      'Sincelejo',
      'Sucre',
      'Tolú',
      'Toluviejo',
    ],
  },
  {
    name: 'Tolima',
    municipalities: [
      'Alpujarra',
      'Alvarado',
      'Ambalema',
      'Anzoátegui',
      'Armero (Guayabal)',
      'Ataco',
      'Cajamarca',
      'Carmen de Apicalá',
      'Casabianca',
      'Chaparral',
      'Coello',
      'Coyaima',
      'Cunday',
      'Dolores',
      'Espinal',
      'Falán',
      'Flandes',
      'Fresno',
      'Guamo',
      'Herveo',
      'Honda',
      'Ibagué',
      'Icononzo',
      'Lérida',
      'Líbano',
      'Mariquita',
      'Melgar',
      'Murillo',
      'Natagaima',
      'Ortega',
      'Palocabildo',
      'Piedras',
      'Planadas',
      'Prado',
      'Purificación',
      'Rioblanco',
      'Roncesvalles',
      'Rovira',
      'Saldaña',
      'San Antonio',
      'San Luis',
      'Santa Isabel',
      'Suárez',
      'Valle de San Juan',
      'Venadillo',
      'Villahermosa',
      'Villarrica',
    ],
  },
  {
    name: 'Vaupés',
    municipalities: [
      'Buenos Aires (Pacoa)',
      'Caruru',
      'Mitú',
      'Morichal (Papunagua)',
      'Taraira',
      'Yavarate',
    ],
  },
  {
    name: 'Vichada',
    municipalities: [
      'Cumaribo',
      'La Primavera',
      'Puerto Carreño',
      'Santa Rosalía',
    ],
  },
  {
    name: 'Valle del Cauca',
    municipalities: [
      'Alcalá',
      'Andalucía',
      'Ansermanutevo',
      'Argelia',
      'Bolívar',
      'Buenaventura',
      'Buga',
      'Bugalagrande',
      'Caicedonia',
      'Cali',
      'Calima (Darién)',
      'Candelaria',
      'Cartago',
      'Dagua',
      'El Águila',
      'El Cairo',
      'El Cerrito',
      'El Dovio',
      'Florida',
      'Ginebra',
      'Guacari',
      'Jamundí',
      'La Cumbre',
      'La Unión',
      'La Victoria',
      'Obando',
      'Palmira',
      'Pradera',
      'Restrepo',
      'Riofrío',
      'Roldanillo',
      'San Pedro',
      'Sevilla',
      'Toro',
      'Trujillo',
      'Tuluá',
      'Ulloa',
      'Versalles',
      'Vijes',
      'Yotoco',
      'Yumbo',
      'Zarzal',
    ],
  },
];

async function seedDepartmentsAndMunicipalities() {
  const AppDataSource = new DataSource({
    type: 'postgres',
    host: process.env.DB_HOST || 'localhost',
    port: parseInt(process.env.DB_PORT || '5236'),
    username: process.env.DB_USERNAME || 'temp-smartpol_user',
    password: process.env.DB_PASSWORD || 'temp-smartpol_password',
    database: process.env.DB_DATABASE || 'temp-smartpol_db',
    entities: ['src/database/entities/*.entity.ts'],
    synchronize: false,
  });

  try {
    await AppDataSource.initialize();
    console.log('✓ Database connected\n');

    const departmentRepository = AppDataSource.getRepository(Department);
    const municipalityRepository = AppDataSource.getRepository(Municipality);

    let departmentsCreated = 0;
    let municipalitiesCreated = 0;
    let departmentsSkipped = 0;
    let municipalitiesSkipped = 0;

    console.log('Seeding departments and municipalities...\n');

    for (const deptData of departmentsData) {
      // Check if department already exists
      const existingDept = await departmentRepository.findOne({
        where: { name: deptData.name },
      });

      let department: Department;

      if (existingDept) {
        console.log(
          `⚠ Department "${deptData.name}" already exists. Skipping...`,
        );
        departmentsSkipped++;
        department = existingDept;
      } else {
        const newDept = departmentRepository.create({ name: deptData.name });
        department = await departmentRepository.save(newDept);
        console.log(`✓ Created department: ${deptData.name}`);
        departmentsCreated++;
      }

      // Add municipalities to the department
      console.log(`\n  Adding municipalities to ${deptData.name}:`);
      for (const municipalityName of deptData.municipalities) {
        const existingMuni = await municipalityRepository.findOne({
          where: {
            name: municipalityName,
            department: { id: department.id },
          },
          relations: ['department'],
        });

        if (existingMuni) {
          console.log(
            `    ⚠ Municipality "${municipalityName}" already exists. Skipping...`,
          );
          municipalitiesSkipped++;
        } else {
          const newMuni = municipalityRepository.create({
            name: municipalityName,
            department: department,
          });
          await municipalityRepository.save(newMuni);
          console.log(`    ✓ Created municipality: ${municipalityName}`);
          municipalitiesCreated++;
        }
      }
      console.log();
    }

    console.log(`\n✅ Seeding completed!`);
    console.log(`   • Departments created: ${departmentsCreated}`);
    console.log(`   • Departments skipped: ${departmentsSkipped}`);
    console.log(`   • Municipalities created: ${municipalitiesCreated}`);
    console.log(`   • Municipalities skipped: ${municipalitiesSkipped}`);
  } catch (error) {
    console.error('❌ Error during seeding:', error);
  } finally {
    await AppDataSource.destroy();
  }
}

seedDepartmentsAndMunicipalities();
